mido: fix a build error and warning
These were fixed with tissot merge but because I skipped it...

 - error: Fix undefined reference to allow external access to function [mdss_dsi_panel.c]
 - warning: Be lazy and remove only the unused variable irrelevant for mido atm [msm8952.c]

Signed-off-by: Rohit Vashisht <rohitv88cf@gmail.com>